spring.application.name=smartExpenseAdvisorProject

# MySQL Railway Database
spring.datasource.url=jdbc:mysql://turntable.proxy.rlwy.net:48349/railway

spring.datasource.username=root
spring.datasource.password=bVtYDaIDrFcBfrpvVbsNZrFFybouZVvh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.address=0.0.0.0
server.port=${PORT:8080}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vanshitwadhera@gmail.com
spring.mail.password=bwnxyivqhdsgacwe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
