spring.application.name=smartExpenseAdvisorProject
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=spring
spring.datasource.password=spring123
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
